// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gpu_available
bool gpu_available();
RcppExport SEXP _acediaR_gpu_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(gpu_available());
    return rcpp_result_gen;
END_RCPP
}
// gpu_info
std::string gpu_info();
RcppExport SEXP _acediaR_gpu_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(gpu_info());
    return rcpp_result_gen;
END_RCPP
}
// gpu_memory_available
double gpu_memory_available();
RcppExport SEXP _acediaR_gpu_memory_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(gpu_memory_available());
    return rcpp_result_gen;
END_RCPP
}
// tensor_softmax_unified
SEXP tensor_softmax_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_softmax_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_softmax_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_argmax_unified
int64_t tensor_argmax_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_argmax_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_argmax_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_tanh_unified
SEXP tensor_tanh_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_tanh_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_tanh_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_sigmoid_unified
SEXP tensor_sigmoid_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_sigmoid_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_sigmoid_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_relu_unified
SEXP tensor_relu_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_relu_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_relu_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_sin_unified
SEXP tensor_sin_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_sin_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_sin_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_cos_unified
SEXP tensor_cos_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_cos_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_cos_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_sub_unified
SEXP tensor_sub_unified(SEXP a_ptr, SEXP b_ptr);
RcppExport SEXP _acediaR_tensor_sub_unified(SEXP a_ptrSEXP, SEXP b_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a_ptr(a_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_ptr(b_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_sub_unified(a_ptr, b_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_div_unified
SEXP tensor_div_unified(SEXP a_ptr, SEXP b_ptr);
RcppExport SEXP _acediaR_tensor_div_unified(SEXP a_ptrSEXP, SEXP b_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a_ptr(a_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_ptr(b_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_div_unified(a_ptr, b_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_add_unified
SEXP tensor_add_unified(SEXP a_ptr, SEXP b_ptr);
RcppExport SEXP _acediaR_tensor_add_unified(SEXP a_ptrSEXP, SEXP b_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a_ptr(a_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_ptr(b_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_add_unified(a_ptr, b_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_mul_unified
SEXP tensor_mul_unified(SEXP a_ptr, SEXP b_ptr);
RcppExport SEXP _acediaR_tensor_mul_unified(SEXP a_ptrSEXP, SEXP b_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a_ptr(a_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_ptr(b_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_mul_unified(a_ptr, b_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_scalar_mul_unified
SEXP tensor_scalar_mul_unified(SEXP tensor_ptr, double scalar);
RcppExport SEXP _acediaR_tensor_scalar_mul_unified(SEXP tensor_ptrSEXP, SEXP scalarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    Rcpp::traits::input_parameter< double >::type scalar(scalarSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_scalar_mul_unified(tensor_ptr, scalar));
    return rcpp_result_gen;
END_RCPP
}
// tensor_scalar_add_unified
SEXP tensor_scalar_add_unified(SEXP tensor_ptr, double scalar);
RcppExport SEXP _acediaR_tensor_scalar_add_unified(SEXP tensor_ptrSEXP, SEXP scalarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    Rcpp::traits::input_parameter< double >::type scalar(scalarSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_scalar_add_unified(tensor_ptr, scalar));
    return rcpp_result_gen;
END_RCPP
}
// tensor_gt_unified
SEXP tensor_gt_unified(SEXP a_ptr, SEXP b_ptr);
RcppExport SEXP _acediaR_tensor_gt_unified(SEXP a_ptrSEXP, SEXP b_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a_ptr(a_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_ptr(b_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_gt_unified(a_ptr, b_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_lt_unified
SEXP tensor_lt_unified(SEXP a_ptr, SEXP b_ptr);
RcppExport SEXP _acediaR_tensor_lt_unified(SEXP a_ptrSEXP, SEXP b_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a_ptr(a_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_ptr(b_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_lt_unified(a_ptr, b_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_eq_unified
SEXP tensor_eq_unified(SEXP a_ptr, SEXP b_ptr);
RcppExport SEXP _acediaR_tensor_eq_unified(SEXP a_ptrSEXP, SEXP b_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a_ptr(a_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_ptr(b_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_eq_unified(a_ptr, b_ptr));
    return rcpp_result_gen;
END_RCPP
}
// create_tensor_unified
SEXP create_tensor_unified(NumericVector data, IntegerVector shape_vec, std::string dtype);
RcppExport SEXP _acediaR_create_tensor_unified(SEXP dataSEXP, SEXP shape_vecSEXP, SEXP dtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type shape_vec(shape_vecSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(create_tensor_unified(data, shape_vec, dtype));
    return rcpp_result_gen;
END_RCPP
}
// create_empty_tensor_unified
SEXP create_empty_tensor_unified(IntegerVector shape_vec, std::string dtype);
RcppExport SEXP _acediaR_create_empty_tensor_unified(SEXP shape_vecSEXP, SEXP dtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type shape_vec(shape_vecSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(create_empty_tensor_unified(shape_vec, dtype));
    return rcpp_result_gen;
END_RCPP
}
// tensor_to_r_unified
NumericVector tensor_to_r_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_to_r_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_to_r_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_shape_unified
IntegerVector tensor_shape_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_shape_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_shape_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_size_unified
size_t tensor_size_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_size_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_size_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_dtype_unified
std::string tensor_dtype_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_dtype_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_dtype_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_info_unified
std::string tensor_info_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_info_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_info_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_to_dtype_unified
SEXP tensor_to_dtype_unified(SEXP tensor_ptr, std::string target_dtype);
RcppExport SEXP _acediaR_tensor_to_dtype_unified(SEXP tensor_ptrSEXP, SEXP target_dtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type target_dtype(target_dtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_to_dtype_unified(tensor_ptr, target_dtype));
    return rcpp_result_gen;
END_RCPP
}
// tensor_synchronize_unified
void tensor_synchronize_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_synchronize_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    tensor_synchronize_unified(tensor_ptr);
    return R_NilValue;
END_RCPP
}
// tensor_is_contiguous_unified
bool tensor_is_contiguous_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_is_contiguous_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_is_contiguous_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_matmul_unified
SEXP tensor_matmul_unified(SEXP a_ptr, SEXP b_ptr);
RcppExport SEXP _acediaR_tensor_matmul_unified(SEXP a_ptrSEXP, SEXP b_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a_ptr(a_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_ptr(b_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_matmul_unified(a_ptr, b_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_outer_product_unified
SEXP tensor_outer_product_unified(SEXP a_ptr, SEXP b_ptr);
RcppExport SEXP _acediaR_tensor_outer_product_unified(SEXP a_ptrSEXP, SEXP b_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a_ptr(a_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_ptr(b_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_outer_product_unified(a_ptr, b_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_matvec_unified
SEXP tensor_matvec_unified(SEXP A_ptr, SEXP v_ptr);
RcppExport SEXP _acediaR_tensor_matvec_unified(SEXP A_ptrSEXP, SEXP v_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type A_ptr(A_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type v_ptr(v_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_matvec_unified(A_ptr, v_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_vecmat_unified
SEXP tensor_vecmat_unified(SEXP v_ptr, SEXP A_ptr);
RcppExport SEXP _acediaR_tensor_vecmat_unified(SEXP v_ptrSEXP, SEXP A_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type v_ptr(v_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type A_ptr(A_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_vecmat_unified(v_ptr, A_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_exp_unified
SEXP tensor_exp_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_exp_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_exp_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_log_unified
SEXP tensor_log_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_log_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_log_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_sqrt_unified
SEXP tensor_sqrt_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_sqrt_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_sqrt_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_slice_add_scalar_unified
void tensor_slice_add_scalar_unified(SEXP tensor_ptr, IntegerVector start_indices, IntegerVector slice_shape, double scalar);
RcppExport SEXP _acediaR_tensor_slice_add_scalar_unified(SEXP tensor_ptrSEXP, SEXP start_indicesSEXP, SEXP slice_shapeSEXP, SEXP scalarSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type start_indices(start_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type slice_shape(slice_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type scalar(scalarSEXP);
    tensor_slice_add_scalar_unified(tensor_ptr, start_indices, slice_shape, scalar);
    return R_NilValue;
END_RCPP
}
// tensor_concat_unified
SEXP tensor_concat_unified(List tensor_list, int axis);
RcppExport SEXP _acediaR_tensor_concat_unified(SEXP tensor_listSEXP, SEXP axisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tensor_list(tensor_listSEXP);
    Rcpp::traits::input_parameter< int >::type axis(axisSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_concat_unified(tensor_list, axis));
    return rcpp_result_gen;
END_RCPP
}
// tensor_stack_unified
SEXP tensor_stack_unified(List tensor_list, int axis);
RcppExport SEXP _acediaR_tensor_stack_unified(SEXP tensor_listSEXP, SEXP axisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tensor_list(tensor_listSEXP);
    Rcpp::traits::input_parameter< int >::type axis(axisSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_stack_unified(tensor_list, axis));
    return rcpp_result_gen;
END_RCPP
}
// tensor_repeat_unified
SEXP tensor_repeat_unified(SEXP tensor_ptr, IntegerVector repeats);
RcppExport SEXP _acediaR_tensor_repeat_unified(SEXP tensor_ptrSEXP, SEXP repeatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type repeats(repeatsSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_repeat_unified(tensor_ptr, repeats));
    return rcpp_result_gen;
END_RCPP
}
// tensor_pad_unified
SEXP tensor_pad_unified(SEXP tensor_ptr, IntegerMatrix pad_width, std::string mode, double value);
RcppExport SEXP _acediaR_tensor_pad_unified(SEXP tensor_ptrSEXP, SEXP pad_widthSEXP, SEXP modeSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type pad_width(pad_widthSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_pad_unified(tensor_ptr, pad_width, mode, value));
    return rcpp_result_gen;
END_RCPP
}
// tensor_sum_unified
double tensor_sum_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_sum_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_sum_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_mean_unified
double tensor_mean_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_mean_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_mean_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_max_unified
double tensor_max_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_max_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_max_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_min_unified
double tensor_min_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_min_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_min_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_prod_unified
double tensor_prod_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_prod_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_prod_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_var_unified
double tensor_var_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_var_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_var_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_view_unified
SEXP tensor_view_unified(SEXP tensor_ptr, IntegerVector new_shape);
RcppExport SEXP _acediaR_tensor_view_unified(SEXP tensor_ptrSEXP, SEXP new_shapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type new_shape(new_shapeSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_view_unified(tensor_ptr, new_shape));
    return rcpp_result_gen;
END_RCPP
}
// tensor_reshape_unified
SEXP tensor_reshape_unified(SEXP tensor_ptr, IntegerVector new_shape);
RcppExport SEXP _acediaR_tensor_reshape_unified(SEXP tensor_ptrSEXP, SEXP new_shapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type new_shape(new_shapeSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_reshape_unified(tensor_ptr, new_shape));
    return rcpp_result_gen;
END_RCPP
}
// tensor_transpose_unified
SEXP tensor_transpose_unified(SEXP tensor_ptr);
RcppExport SEXP _acediaR_tensor_transpose_unified(SEXP tensor_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_transpose_unified(tensor_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tensor_permute_unified
SEXP tensor_permute_unified(SEXP tensor_ptr, IntegerVector dims);
RcppExport SEXP _acediaR_tensor_permute_unified(SEXP tensor_ptrSEXP, SEXP dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tensor_ptr(tensor_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dims(dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(tensor_permute_unified(tensor_ptr, dims));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_acediaR_gpu_available", (DL_FUNC) &_acediaR_gpu_available, 0},
    {"_acediaR_gpu_info", (DL_FUNC) &_acediaR_gpu_info, 0},
    {"_acediaR_gpu_memory_available", (DL_FUNC) &_acediaR_gpu_memory_available, 0},
    {"_acediaR_tensor_softmax_unified", (DL_FUNC) &_acediaR_tensor_softmax_unified, 1},
    {"_acediaR_tensor_argmax_unified", (DL_FUNC) &_acediaR_tensor_argmax_unified, 1},
    {"_acediaR_tensor_tanh_unified", (DL_FUNC) &_acediaR_tensor_tanh_unified, 1},
    {"_acediaR_tensor_sigmoid_unified", (DL_FUNC) &_acediaR_tensor_sigmoid_unified, 1},
    {"_acediaR_tensor_relu_unified", (DL_FUNC) &_acediaR_tensor_relu_unified, 1},
    {"_acediaR_tensor_sin_unified", (DL_FUNC) &_acediaR_tensor_sin_unified, 1},
    {"_acediaR_tensor_cos_unified", (DL_FUNC) &_acediaR_tensor_cos_unified, 1},
    {"_acediaR_tensor_sub_unified", (DL_FUNC) &_acediaR_tensor_sub_unified, 2},
    {"_acediaR_tensor_div_unified", (DL_FUNC) &_acediaR_tensor_div_unified, 2},
    {"_acediaR_tensor_add_unified", (DL_FUNC) &_acediaR_tensor_add_unified, 2},
    {"_acediaR_tensor_mul_unified", (DL_FUNC) &_acediaR_tensor_mul_unified, 2},
    {"_acediaR_tensor_scalar_mul_unified", (DL_FUNC) &_acediaR_tensor_scalar_mul_unified, 2},
    {"_acediaR_tensor_scalar_add_unified", (DL_FUNC) &_acediaR_tensor_scalar_add_unified, 2},
    {"_acediaR_tensor_gt_unified", (DL_FUNC) &_acediaR_tensor_gt_unified, 2},
    {"_acediaR_tensor_lt_unified", (DL_FUNC) &_acediaR_tensor_lt_unified, 2},
    {"_acediaR_tensor_eq_unified", (DL_FUNC) &_acediaR_tensor_eq_unified, 2},
    {"_acediaR_create_tensor_unified", (DL_FUNC) &_acediaR_create_tensor_unified, 3},
    {"_acediaR_create_empty_tensor_unified", (DL_FUNC) &_acediaR_create_empty_tensor_unified, 2},
    {"_acediaR_tensor_to_r_unified", (DL_FUNC) &_acediaR_tensor_to_r_unified, 1},
    {"_acediaR_tensor_shape_unified", (DL_FUNC) &_acediaR_tensor_shape_unified, 1},
    {"_acediaR_tensor_size_unified", (DL_FUNC) &_acediaR_tensor_size_unified, 1},
    {"_acediaR_tensor_dtype_unified", (DL_FUNC) &_acediaR_tensor_dtype_unified, 1},
    {"_acediaR_tensor_info_unified", (DL_FUNC) &_acediaR_tensor_info_unified, 1},
    {"_acediaR_tensor_to_dtype_unified", (DL_FUNC) &_acediaR_tensor_to_dtype_unified, 2},
    {"_acediaR_tensor_synchronize_unified", (DL_FUNC) &_acediaR_tensor_synchronize_unified, 1},
    {"_acediaR_tensor_is_contiguous_unified", (DL_FUNC) &_acediaR_tensor_is_contiguous_unified, 1},
    {"_acediaR_tensor_matmul_unified", (DL_FUNC) &_acediaR_tensor_matmul_unified, 2},
    {"_acediaR_tensor_outer_product_unified", (DL_FUNC) &_acediaR_tensor_outer_product_unified, 2},
    {"_acediaR_tensor_matvec_unified", (DL_FUNC) &_acediaR_tensor_matvec_unified, 2},
    {"_acediaR_tensor_vecmat_unified", (DL_FUNC) &_acediaR_tensor_vecmat_unified, 2},
    {"_acediaR_tensor_exp_unified", (DL_FUNC) &_acediaR_tensor_exp_unified, 1},
    {"_acediaR_tensor_log_unified", (DL_FUNC) &_acediaR_tensor_log_unified, 1},
    {"_acediaR_tensor_sqrt_unified", (DL_FUNC) &_acediaR_tensor_sqrt_unified, 1},
    {"_acediaR_tensor_slice_add_scalar_unified", (DL_FUNC) &_acediaR_tensor_slice_add_scalar_unified, 4},
    {"_acediaR_tensor_concat_unified", (DL_FUNC) &_acediaR_tensor_concat_unified, 2},
    {"_acediaR_tensor_stack_unified", (DL_FUNC) &_acediaR_tensor_stack_unified, 2},
    {"_acediaR_tensor_repeat_unified", (DL_FUNC) &_acediaR_tensor_repeat_unified, 2},
    {"_acediaR_tensor_pad_unified", (DL_FUNC) &_acediaR_tensor_pad_unified, 4},
    {"_acediaR_tensor_sum_unified", (DL_FUNC) &_acediaR_tensor_sum_unified, 1},
    {"_acediaR_tensor_mean_unified", (DL_FUNC) &_acediaR_tensor_mean_unified, 1},
    {"_acediaR_tensor_max_unified", (DL_FUNC) &_acediaR_tensor_max_unified, 1},
    {"_acediaR_tensor_min_unified", (DL_FUNC) &_acediaR_tensor_min_unified, 1},
    {"_acediaR_tensor_prod_unified", (DL_FUNC) &_acediaR_tensor_prod_unified, 1},
    {"_acediaR_tensor_var_unified", (DL_FUNC) &_acediaR_tensor_var_unified, 1},
    {"_acediaR_tensor_view_unified", (DL_FUNC) &_acediaR_tensor_view_unified, 2},
    {"_acediaR_tensor_reshape_unified", (DL_FUNC) &_acediaR_tensor_reshape_unified, 2},
    {"_acediaR_tensor_transpose_unified", (DL_FUNC) &_acediaR_tensor_transpose_unified, 1},
    {"_acediaR_tensor_permute_unified", (DL_FUNC) &_acediaR_tensor_permute_unified, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_acediaR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
