# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gpu_available <- function() {
    .Call(`_acediaR_gpu_available`)
}

gpu_info <- function() {
    .Call(`_acediaR_gpu_info`)
}

gpu_memory_available <- function() {
    .Call(`_acediaR_gpu_memory_available`)
}

tensor_sub_unified <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_tensor_sub_unified`, a_ptr, b_ptr)
}

tensor_div_unified <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_tensor_div_unified`, a_ptr, b_ptr)
}

create_tensor_unified <- function(data, shape_vec, dtype = "float32") {
    .Call(`_acediaR_create_tensor_unified`, data, shape_vec, dtype)
}

create_empty_tensor_unified <- function(shape_vec, dtype = "float32") {
    .Call(`_acediaR_create_empty_tensor_unified`, shape_vec, dtype)
}

tensor_to_r_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_to_r_unified`, tensor_ptr)
}

tensor_shape_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_shape_unified`, tensor_ptr)
}

tensor_size_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_size_unified`, tensor_ptr)
}

tensor_dtype_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_dtype_unified`, tensor_ptr)
}

tensor_info_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_info_unified`, tensor_ptr)
}

tensor_to_dtype_unified <- function(tensor_ptr, target_dtype) {
    .Call(`_acediaR_tensor_to_dtype_unified`, tensor_ptr, target_dtype)
}

tensor_add_unified <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_tensor_add_unified`, a_ptr, b_ptr)
}

tensor_scalar_mul_unified <- function(tensor_ptr, scalar) {
    .Call(`_acediaR_tensor_scalar_mul_unified`, tensor_ptr, scalar)
}

tensor_sum_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_sum_unified`, tensor_ptr)
}

tensor_synchronize_unified <- function(tensor_ptr) {
    invisible(.Call(`_acediaR_tensor_synchronize_unified`, tensor_ptr))
}

tensor_is_contiguous_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_is_contiguous_unified`, tensor_ptr)
}

tensor_mul_unified <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_tensor_mul_unified`, a_ptr, b_ptr)
}

tensor_matmul_unified <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_tensor_matmul_unified`, a_ptr, b_ptr)
}

tensor_view_unified <- function(tensor_ptr, new_shape) {
    .Call(`_acediaR_tensor_view_unified`, tensor_ptr, new_shape)
}

tensor_scalar_add_unified <- function(tensor_ptr, scalar) {
    .Call(`_acediaR_tensor_scalar_add_unified`, tensor_ptr, scalar)
}

tensor_transpose_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_transpose_unified`, tensor_ptr)
}

tensor_permute_unified <- function(tensor_ptr, dims) {
    .Call(`_acediaR_tensor_permute_unified`, tensor_ptr, dims)
}

