# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gpu_available <- function() {
    .Call(`_acediaR_gpu_available`)
}

gpu_info <- function() {
    .Call(`_acediaR_gpu_info`)
}

gpu_memory_available <- function() {
    .Call(`_acediaR_gpu_memory_available`)
}

tensor_softmax_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_softmax_unified`, tensor_ptr)
}

tensor_tanh_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_tanh_unified`, tensor_ptr)
}

tensor_sigmoid_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_sigmoid_unified`, tensor_ptr)
}

tensor_relu_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_relu_unified`, tensor_ptr)
}

tensor_sin_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_sin_unified`, tensor_ptr)
}

tensor_cos_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_cos_unified`, tensor_ptr)
}

tensor_sub_unified <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_tensor_sub_unified`, a_ptr, b_ptr)
}

tensor_div_unified <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_tensor_div_unified`, a_ptr, b_ptr)
}

tensor_add_unified <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_tensor_add_unified`, a_ptr, b_ptr)
}

tensor_mul_unified <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_tensor_mul_unified`, a_ptr, b_ptr)
}

tensor_scalar_mul_unified <- function(tensor_ptr, scalar) {
    .Call(`_acediaR_tensor_scalar_mul_unified`, tensor_ptr, scalar)
}

tensor_scalar_add_unified <- function(tensor_ptr, scalar) {
    .Call(`_acediaR_tensor_scalar_add_unified`, tensor_ptr, scalar)
}

tensor_gt_unified <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_tensor_gt_unified`, a_ptr, b_ptr)
}

tensor_lt_unified <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_tensor_lt_unified`, a_ptr, b_ptr)
}

tensor_eq_unified <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_tensor_eq_unified`, a_ptr, b_ptr)
}

create_tensor_unified <- function(data, shape_vec, dtype = "float32") {
    .Call(`_acediaR_create_tensor_unified`, data, shape_vec, dtype)
}

create_empty_tensor_unified <- function(shape_vec, dtype = "float32") {
    .Call(`_acediaR_create_empty_tensor_unified`, shape_vec, dtype)
}

tensor_to_r_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_to_r_unified`, tensor_ptr)
}

tensor_shape_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_shape_unified`, tensor_ptr)
}

tensor_size_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_size_unified`, tensor_ptr)
}

tensor_dtype_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_dtype_unified`, tensor_ptr)
}

tensor_info_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_info_unified`, tensor_ptr)
}

tensor_to_dtype_unified <- function(tensor_ptr, target_dtype) {
    .Call(`_acediaR_tensor_to_dtype_unified`, tensor_ptr, target_dtype)
}

tensor_synchronize_unified <- function(tensor_ptr) {
    invisible(.Call(`_acediaR_tensor_synchronize_unified`, tensor_ptr))
}

tensor_is_contiguous_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_is_contiguous_unified`, tensor_ptr)
}

tensor_matmul_unified <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_tensor_matmul_unified`, a_ptr, b_ptr)
}

tensor_outer_product_unified <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_tensor_outer_product_unified`, a_ptr, b_ptr)
}

tensor_matvec_unified <- function(A_ptr, v_ptr) {
    .Call(`_acediaR_tensor_matvec_unified`, A_ptr, v_ptr)
}

tensor_vecmat_unified <- function(v_ptr, A_ptr) {
    .Call(`_acediaR_tensor_vecmat_unified`, v_ptr, A_ptr)
}

tensor_exp_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_exp_unified`, tensor_ptr)
}

tensor_log_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_log_unified`, tensor_ptr)
}

tensor_sqrt_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_sqrt_unified`, tensor_ptr)
}

tensor_abs_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_abs_unified`, tensor_ptr)
}

tensor_slice_add_scalar_unified <- function(tensor_ptr, start_indices, slice_shape, scalar) {
    invisible(.Call(`_acediaR_tensor_slice_add_scalar_unified`, tensor_ptr, start_indices, slice_shape, scalar))
}

tensor_concat_unified <- function(tensor_list, axis = 1L) {
    .Call(`_acediaR_tensor_concat_unified`, tensor_list, axis)
}

tensor_stack_unified <- function(tensor_list, axis = 1L) {
    .Call(`_acediaR_tensor_stack_unified`, tensor_list, axis)
}

tensor_repeat_unified <- function(tensor_ptr, repeats) {
    .Call(`_acediaR_tensor_repeat_unified`, tensor_ptr, repeats)
}

tensor_pad_unified <- function(tensor_ptr, pad_width, mode = "constant", value = 0) {
    .Call(`_acediaR_tensor_pad_unified`, tensor_ptr, pad_width, mode, value)
}

tensor_sum_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_sum_unified`, tensor_ptr)
}

tensor_mean_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_mean_unified`, tensor_ptr)
}

tensor_max_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_max_unified`, tensor_ptr)
}

tensor_min_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_min_unified`, tensor_ptr)
}

tensor_prod_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_prod_unified`, tensor_ptr)
}

tensor_var_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_var_unified`, tensor_ptr)
}

tensor_sum_axis <- function(tensor_ptr, axis = NULL, keep_dims = FALSE) {
    .Call(`_acediaR_tensor_sum_axis`, tensor_ptr, axis, keep_dims)
}

tensor_mean_axis <- function(tensor_ptr, axis = NULL, keep_dims = FALSE) {
    .Call(`_acediaR_tensor_mean_axis`, tensor_ptr, axis, keep_dims)
}

tensor_max_axis <- function(tensor_ptr, axis = NULL, keep_dims = FALSE) {
    .Call(`_acediaR_tensor_max_axis`, tensor_ptr, axis, keep_dims)
}

tensor_min_axis <- function(tensor_ptr, axis = NULL, keep_dims = FALSE) {
    .Call(`_acediaR_tensor_min_axis`, tensor_ptr, axis, keep_dims)
}

tensor_prod_axis <- function(tensor_ptr, axis = NULL, keep_dims = FALSE) {
    .Call(`_acediaR_tensor_prod_axis`, tensor_ptr, axis, keep_dims)
}

tensor_var_axis <- function(tensor_ptr, axis = NULL, keep_dims = FALSE) {
    .Call(`_acediaR_tensor_var_axis`, tensor_ptr, axis, keep_dims)
}

tensor_argmax_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_argmax_unified`, tensor_ptr)
}

tensor_argmin_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_argmin_unified`, tensor_ptr)
}

tensor_argmax_axis <- function(tensor_ptr, axis, keep_dims = FALSE) {
    .Call(`_acediaR_tensor_argmax_axis`, tensor_ptr, axis, keep_dims)
}

tensor_argmin_axis <- function(tensor_ptr, axis, keep_dims = FALSE) {
    .Call(`_acediaR_tensor_argmin_axis`, tensor_ptr, axis, keep_dims)
}

tensor_view_unified <- function(tensor_ptr, new_shape) {
    .Call(`_acediaR_tensor_view_unified`, tensor_ptr, new_shape)
}

tensor_reshape_unified <- function(tensor_ptr, new_shape) {
    .Call(`_acediaR_tensor_reshape_unified`, tensor_ptr, new_shape)
}

tensor_transpose_unified <- function(tensor_ptr) {
    .Call(`_acediaR_tensor_transpose_unified`, tensor_ptr)
}

tensor_permute_unified <- function(tensor_ptr, dims) {
    .Call(`_acediaR_tensor_permute_unified`, tensor_ptr, dims)
}

