# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

as_gpuVector <- function(x) {
    .Call(`_acediaR_as_gpuVector`, x)
}

as_vector_gpuVector <- function(gpu_vec_ptr) {
    .Call(`_acediaR_as_vector_gpuVector`, gpu_vec_ptr)
}

gpu_add_rcpp <- function(a_ptr, b_ptr) {
    .Call(`_acediaR_gpu_add_rcpp`, a_ptr, b_ptr)
}

print_gpuVector <- function(gpu_vec_ptr) {
    invisible(.Call(`_acediaR_print_gpuVector`, gpu_vec_ptr))
}

gpuVector_size <- function(gpu_vec_ptr) {
    .Call(`_acediaR_gpuVector_size`, gpu_vec_ptr)
}

gpuVector_empty <- function(gpu_vec_ptr) {
    .Call(`_acediaR_gpuVector_empty`, gpu_vec_ptr)
}

